# Generated by Django 4.2.1 on 2023-08-07 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_friend_profile_friends"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("sent", models.BooleanField(default=False)),
                ("time_sent", models.DateTimeField(auto_now_add=True)),
                (
                    "msg_recseiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="msg_receiver",
                        to="chat.profile",
                    ),
                ),
                (
                    "msg_sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="msg_sender",
                        to="chat.profile",
                    ),
                ),
            ],
        ),
    ]
