# Generated by Django 4.2.1 on 2023-08-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatmessage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatmessage",
            old_name="msg_recseiver",
            new_name="msg_receiver",
        ),
    ]
